### ISSUE TITLE
translate label?!

### ISSUE THREAD

**Issue by tdpt** [nielslange/smntcs-show-sale-price-date-for-woocommerce#16]
Nice plugin and Woocommerce should have this option by default.

I see you show how to change the label, but if we update the plugin in future we will lose that customization. Is there a way to change it on a translations file?

Nice work. Thank you.

**Comment by nielslange** [comment]
Hello @tdpt 👋 You can translate the label by adding the following code to the functions.php file within your theme:

```
add_filter( 'sale_date_label', 'my_custom_sale_date_label' );
function my_custom_sale_date_label() {
    return 'My custom title;
}
```

Please let me know if that works as expected. 😉

**Comment by tdpt** [comment]
Thank you, I will try that.

Niels Lange <notifications@github.com> escreveu no dia quinta, 7/05/2020
à(s) 14:39:

**Comment by nielslange** [comment]
Sounds good, @tdpt. I'm going to close this issue for now. But feel free to open another one if you have another question.

**Comment by tdpt** [comment]
Niels

Sorry, but I have this problem, and maybe you can help me easely:  I want
to label with "Promoção até" but using does portuguese special
characters wordpress don't let me save the file. I have to edit it and
upload by ftp :(

Is there any way I can edit it on the admin theme editor on Wordpress?

Thank you

Niels Lange <notifications@github.com> escreveu no dia sexta, 8/05/2020
à(s) 14:22:

**Comment by nielslange** [comment]
Hello @tdpt 👋

> Is there any way I can edit it on the admin theme editor on Wordpress?

I'm going to move the label to the customizer, so that it can be edited there. I'll let you know once I deployed the new version of the plugin. 😉

**Comment by nielslange** [comment]
Hello @tdpt 👋I just deployed a new version of the plugin, which allows you to add the label directly via `WP Admin → Appearance → WooCommerce → Show Sale Price Date` as seen on the following screenshot:

![#16-after](https://user-images.githubusercontent.com/3323310/81472440-4c9b2200-9222-11ea-8f5f-c4951ce0899d.png)

If you like the plugin and this enhancement, it would be great if you would rate the plugin via https://wordpress.org/support/plugin/smntcs-show-sale-price-date-for-woocommerce/reviews/#new-post 😁

**Comment by tdpt** [comment]
Now is perfect ;)

Thank you

Niels Lange <notifications@github.com> escreveu no dia sábado, 9/05/2020
à(s) 12:25:
